### ISSUE TITLE
Create Views: Calendar View (in Sidebar??)

### ISSUE THREAD

**Issue by liechtia** [jocelynthode/coachup#15]
**Description :** 
* list of dates

**Priority :** medium

**Reviewer :** @simonbru 

**Effort Planned :** 4h

**Actual Effort :** 6h

**Comment by liechtia** [comment]
74f466454cb20bb6d6ad84f2866723910ddf610e
sorry, this somehow includes other branches' changes as well... my changes for this are just in user.rb and application.html.erb

**Comment by simonbru** [comment]
When you do `occ = schedule.occurrences(Date.today + 1.year)` it doesn't honor the end date of the course (it still give occurences happening after the end date). I think you should be able to do something like `schedule.occurs_between?(Date.today, sub.course.ends_at)`.

In user.rb you can replace lines 59 to 60 with 
```
all_dates.take 10
```
because it works even if the list is smaller than 10, and right now the method returns nil if there are 0<n<10 courses (which means "You have no sessions within a year!" in the view).


(I think you forgot to remove `<% puts @sessions.nil? %>` in the view :) )

**Comment by liechtia** [comment]
it doesn't work with the all_dates.take(10)... i tried a couple of different ways..
