### ISSUE TITLE
user authentication

### ISSUE THREAD

**Issue by liechtia** [jocelynthode/coachup#2]
**Description :**
* Homebrewed authentication with the cybercoach server
* Provide filter to check if a user is authenticated or not

**Priority :** High
**Reviewer :** @jocelynthode

**Effort Planned :** 4

**Actual Effort :** 8

**Comment by simonbru** [comment]
I see that you didn't add (yet?) this filter in applications_controller.rb:
```before_action :authenticate_user!```
I just want to know if it is temporary or not, because the auth checks in other controllers have to be declared differently depending on whether this filter is applied application-wide or not.

**Comment by jungomi** [comment]
I forgot it, and will add it later.

**Comment by jungomi** [comment]
We are currently using device for the authentication, but it might be a good idea to drop it an only use the CyberCoach service.

**Comment by jungomi** [comment]
Moving to Sprint 2.
Same reason as in issue #18

**Comment by jungomi** [comment]
315fadc881ca3f93907d15c8f3d9d887b6640aeb

**Comment by jocelynthode** [comment]
* Add a skip_before_action require_login in the index controller since we want a user to be able to see the index even without being logged in
* Flash error when wrong password or username give is not appearing

Otherwise it's fine, I guess you can close the issue after these two are fixed and push it to development
