### ISSUE TITLE
Refactor Cybercoach request

### ISSUE THREAD

**Issue by liechtia** [jocelynthode/coachup#47]
Try to make it modular and usable everywhere

**Comment by liechtia** [comment]
and the smartest one ;)

**Comment by jocelynthode** [comment]
https://github.com/jungomi/coach_client

**Comment by jungomi** [comment]
refactored the user part to use coach_client gem 8d4247690ed252faff2841a09061b98ffaeaad2b

**Comment by jungomi** [comment]
Btw. the partnerships model now seems redundant, and everything could be done in the controller.

**Comment by simonbru** [comment]
Yeah, I agree that most of the model's code is now redundant.
The only value it adds compared to the gem is an easy way to get all the partnerships confirmed by a particular user. Maybe this could be done in a method of the user's model since we already put data related to Cybercoach in the user model ?
Otherwise we probably would have to put it in application_controller since we need it in multiple places.

**Comment by jungomi** [comment]
I removed that from the current model (the approved by filter), but it is even easier with the gem:
```ruby
CoachClient::Partnership.list(coach_client, all: true) do |p|
  p.update
  p.user1_confirmed
end
```
(Or do some other filtering, and skip the update if the user is not present (either user1 or user2), because update is a get request and it's slow). The block is used as a filter and therefore adds the partnership if the return value is truthy.

Also to get the partnerships from a specific user you can request the user resource (it contains all partnerships of that user, no need to traverse all partnerships)
The gem provides a getter to the partnerships in the user resource (just need to call update before)

**Comment by simonbru** [comment]
I had found the getter for retrieving every user's partnerships, but I didn't see that it was accepting a block as a filter. :)

However user1 is not always == user, that's why I had to do one check for user1 and one for user2. For example user is user2 when the partnership was first created by the other user. See newuser31 to see this in action:
```curl 'http://diufvm31.unifr.ch:8090/CyberCoachServer/resources/users/newuser31/?size=50' -H 'Authorization: Basic bmV3dXNlcjMxOm5ld3VzZXI=' -H 'Accept: application/json' | jq```

**Comment by jungomi** [comment]
Yes, I know that CyberCoach does not always have the user1 as the user, but the gem does, so you don't need to worry about that. Which is also more logical, since there is no distinction between user1;user2 and user2;user1 (as far as I could tell).

**Comment by simonbru** [comment]
Ohh right sorry! I didn't understard this before. It seems you really thought all of this through. :+1:
