### ISSUE TITLE
upload and delete profile picture

### ISSUE THREAD

**Issue by liechtia** [jocelynthode/coachup#70]
**Description :** add possiblility to upload and delete images 

**Priority :** high

**Reviewer :** @simonbru 

**Effort Planned :** 6h

**Actual Effort :** 4h

**Comment by liechtia** [comment]
i'll try to do it with carrierwave and cloudinary so that the pictures don't get deleted by heroku

**Comment by liechtia** [comment]
594d978b13ca9051fcff67cdfb934ab6a2ba2c4d

**Comment by simonbru** [comment]
The DB migration fails because the binaries table is not created in your commit (you probably already deleted the migration file that creates it), but it still tries to delete an non-existent table.
I think you can simply remove the 20151106130007_drop_binaries_table.rb migration file.

Also this is a small detail, but in users/_form.html.erb I think you should replace
```
<%= f.label 'Profile Picture: ' %>
```
With this:
```
<%= f.label :avatar, 'Profile Picture' %>
```
So the label tag is link to the upload input tag, and the label text follows the same convention as the other labels in the form.

Otherwise it works well! It is nice that you resize the picture in two different sizes at upload time.
Maybe add a way to edit/delete the picture once logged in (but we can still see that next sprint I guess).
